-- AlterTable
ALTER TABLE "Coin" ADD COLUMN "totalSupply" INTEGER NOT NULL DEFAULT 1000000000;
ALTER TABLE "Coin" ADD COLUMN "migrated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Coin" ADD COLUMN "migratedAt" TIMESTAMP(3);
